#!/bin/bash
# Script that is used to run automated login

# Check if app is running on local machine or RPi
if [ "$USER" == "anino1996" ]; then
	echo "Running on Anino's Mac";
	cd ~/Python/attendance_automation;

else

	echo "Running on Anino's Pi";
	cd /home/pi/Documents/attendance_automation;

fi;

# Change path to application directory and activate virtual environment
APP_PATH=$(pwd)/att_auto/bin/python3;
source ./att_auto/bin/activate;

if [ "$(which python3)" == "$APP_PATH" ]; then

	echo "Virtual Environment Activated";

else

	echo "Failed to activate virtual environment";

fi;

# Run login application
./att_auto/bin/python3 ntflxLogin.py;

deactivate;

echo "All done";

exit;

