#!/bin/bash

source att_auto/bin/activate

if [ "$USER" == "anino1996" ]; then

	echo "Running on Anino's Mac";
	cd ~/Python/attendance_automation;
	/usr/bin/python3 ntflxLogin.py;

else 
	echo "Running on Anino's Pi";
	cd /home/pi/Documents/attendance_automation;
	python3 ntflxLogin.py;
fi;

deactivate;

echo "All done";


exit;

